--- DAP (Debug Adapter Protocol) keymaps.
--- All DAP keymaps are registered in `plugins/dap.lua` inside the plugin's
--- config function to ensure nvim-dap and nvim-dap-ui are fully loaded
--- before any keybindings reference them. This file is intentionally empty.
--- @module keymaps.dap
--- @see plugins.dap
